name: Gitlab Mirror

on: push

jobs:
  do_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: false
      - uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: 'https://gitlab.osti.gov/genesis/Swarm.git/'
          GIT_USERNAME: raffenet
          GIT_PASSWORD: ${{ secrets.OSTI_GITLAB_TOKEN }}
